
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

import webbrowser as web
from pathlib import Path
import subprocess
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/macbook/Desktop/vscode/py/build/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.title("web viewer")

window.geometry("1280x832")
window.configure(bg = "#1E1E1E")


canvas = Canvas(
    window,
    bg = "#1E1E1E",
    height = 832,
    width = 1280,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    640.0,
    41.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    640.0,
    457.0,
    image=image_image_2
)
url=["https://www.youtube.com",'https://www.google.com','https://scratch.mit.edu','https://mail.google.com',"https://onedrive.live.com",'https://unsplash.com','https://www.figma.com','opera','safari','calculator','maps','chess','notes','anaconda-navigator','VScode','idle','launchpad','photos']

def search():
 
    value=entry_1.get()
    value=value.lower()
    
    if value=="youtube" :
        subprocess.call(["say","Opening youtube"])
        web.open_new(url[0])
        
    if value=="google":
         subprocess.call(["say","Opening google"])
         web.open(url[1])
         
    if value=="scratch":
         subprocess.call(["say","Opening scratch"])
         web.open(url[2])
         
    if value=="gmail":
         subprocess.call(["say","Opening gmail"])
         web.open(url[3])
         
    if value== "one drive":
         subprocess.call(["say","Opening onedrive"])
         web.open(url[4])
         
    if value=="images":
         subprocess.call(["say","Opening unsplash"]) 
         web.open(url[5])
          
    if value=="designes" :
         subprocess.call(["say","Opening figma"])
         web.open(url[6]) 
         
    if value=="opera":
        subprocess.call(["say","Opening opera"])
        subprocess.Popen("open -a "+url[7],shell=True)
        
    if value=="web1":
        subprocess.call(["say","Opening safari"])
        subprocess.Popen("open -a "+url[8],shell=True)
        
    if value=="calculator":
        subprocess.call(["say","Opening calculator"])
        subprocess.Popen("open -a "+url[9],shell=True)
        
    if value=="map":
        subprocess.call(["say","Opening maps"])
        subprocess.Popen("open -a "+url[10],shell=True)
        
    if value=="game1":
        subprocess.call(["say","Opening chess"])
        subprocess.Popen("open -a "+url[11],shell=True)
        
    if value=="note":
        subprocess.call(["say","Opening notes"])
        subprocess.Popen("open -a "+url[12],shell=True)
        
    if value=="ide launcher":
        subprocess.call(["say","Opening Anaconda-Navigator"])
        subprocess.Popen("open -a "+url[13],shell=True)
        
    if value=="vscode":
        subprocess.call(["say","Opening Visual studio Code"])
        subprocess.Popen("open -a "+url[14],shell=True)
    if value=="python":
        subprocess.call(["say","Opening Python "])
        subprocess.Popen("open -a "+url[15],shell=True)
    if value=="apps":
        subprocess.call(["say","Opening launchpad"])
        subprocess.Popen("open -a "+url[16],shell=True)  
    if value=="photos":
        subprocess.call(["say","Opening photos"])
        subprocess.Popen("open -a "+url[17],shell=True)    
    elif value=="":
     print("Sorry,Chould not able to find it.")
     subprocess.call(["say","Sorry,I am not able to find it."])
     
  
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=search,
    relief="flat"
)
button_1.place(
    x=519.0,
    y=568.0,
    width=244.0,
    height=75.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    640.0,
    199.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#000000",
    fg="#ffffff",
    highlightthickness=0
)
entry_1.place(
    x=379.0,
    y=180.0,
    width=522.0,
    height=37.0
)
window.resizable(False,True)
window.mainloop()
